FROM cypress/base:16.14.0-slim

# Create app directory
WORKDIR /usr/app/client
RUN chown -R node:node /usr/app/client

USER root
RUN apt-get update && apt-get -y install procps
COPY package*.json ./
USER node
RUN npm ci
COPY . .
