FROM cypress/base:16.14.0-slim

# Create app directory
WORKDIR /usr/app/client

USER root
# RUN npm install -g npm@latest
RUN npm install -g typescript cypress
RUN apt-get update && apt-get -y install procps

RUN chown -R node:node /usr/app/client
USER node
COPY package*.json ./
# USER node
RUN npm ci
# RUN npm install
COPY . .
# CMD ["npm", "run", "e2e:ci"]