version: '3.8'

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    volumes:
      - ../api:/usr/app/api 
      - /usr/app/api/node_modules
    ports:
      - 8080:8080