version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test_unit
    ports:
      - '5432:5430'
    volumes:
      - ../api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    depends_on:
      - db
    build:
      context: ../api
      dockerfile: Dockerfile.test
    ports:
      - 8080:8080
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    env_file:
      - ../env/api/.env.test.unit
    environment:
      - DB_NAME=db_test_unit
      - DB_Port=5430
      - DB_HOST=db
    command: npm run test
