version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test_e2e
    ports:
      - "5432:5432"
  api:
    depends_on:
      - db
    build:
      context: ../api
      dockerfile: Dockerfile.test
    ports:
      - 8080:8080
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    env_file:
      - ../env/api/.env.test.e2e
    restart: always
  cypress:
    build:
      context: ../client
      dockerfile: Dockerfile.test
    env_file:
      - ../env/client/.env.test.e2e
    command: "npm run e2e:ci"
    ports:
      - 3000:3000
