version: "3"
#version: '3.8'

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    env_file:
      - ../env/api/.env.dev
    restart: always
  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    env_file:
      - ../env/client/.env.dev
    ports:
      - 3000:3000
    volumes:
      - ../client:/usr/app/client
      - /urs/app/client/node_modules
    restart: always
networks:
  default:
    name: pj-net
