version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    env_file:
      - ../env/api/.env.dev
    restart: always
  client:
    build:
      context: ../client/react
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    env_file:
      - ../env/client/.env.dev
    ports:
      - 3000:3000
    volumes:
      - ../client/react:/usr/app/client/react
      - /urs/app/client/react/node_modules
    restart: always
volumes:
  db:
