version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    ports:
      - 5432:5432
    volumes:
      - ../api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
