version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test_e2e
    ports:
      - '5432:5432'
    volumes:
      - ../api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    depends_on:
      - db
    build:
      context: ../api
      dockerfile: Dockerfile.test
    ports:
      - 8080:8082
    env_file:
      - ../env/api/.env.test.e2e
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_NAME=db_test_e2e
      - JWT_SECRET=${JWT_SECRET}
    command: 'npm run dev'
  cypress:
    build:
      context: ../client/react
      dockerfile: Dockerfile.test
    depends_on:
      - api
    env_file:
      - ../env/client/.env.test.e2e
    ports:
      - 3000:3000
    volumes:
      - ../client/react:/usr/app/client/react
      - /urs/app/client/react/node_modules
    command: 'npm run e2e:ci'
