version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    ports:
      - "5432:5432"
    # volumes:
    #   - db:/var/lib/postgresql/data
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    env_file:
      - ../env/api/.env.dev
    restart: always
    # command: tail -F nonExistingFile
#   client:
#     build:
#       context: ../client
#       dockerfile: Dockerfile.dev
#     env_file:
#       - ../env/client/.env.dev
#     ports:
#       - 3000:3000
#     volumes:
#       - ../client:/usr/app/client
#       - /urs/app/client/node_modules
#     restart: always

# networks:
#   default:
#     name: pj-net
volumes:
  db:
    driver: local
