version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_unit_test
    ports:
      - '5432:5432'
    volumes:
      - ../api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    depends_on:
      - db
    build:
      context: ../api
      dockerfile: Dockerfile.test
    ports:
      - 8081:8081
      - 9229:9229
    env_file:
      - ../env/api/.env.test.unit.dev
    volumes:
      - ../api:/usr/app/api
      - /usr/app/api/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_unit_test
      - JWT_SECRET=${JWT_SECRET}
    command: sh -c "./scripts/shell/wait-for-it.sh db:5432; tail -f /dev/null"
