FROM node:16-bullseye-slim

WORKDIR /usr/app/api
RUN chown -R node:node /usr/app/api

RUN npm install -g npm@latest
RUN npm install -g npm-run-all
COPY package*.json ./
RUN npm install

COPY . .

CMD npm run dev