name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose -f dc/docker-compose.test.unit.yml -p unit up --exit-code-from api

      - name: Stop containers
        run: docker-compose -f dc/docker-compose.test.unit.yml -p unit down --remove-orphans
