name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Install Node
      #   uses: actions/setup-node@v1

      - name: Start containers
        run: docker-compose -f "dc/docker-compose.dev.yml" -f "dc/docker-compose.test.unit.yml" up --build --exit-code-from api

      - name: Stop containers
        # if: always()
        run: docker-compose -f "dc/docker-compose.dev.yml" -f "dc/docker-compose.test.unit.yml" down
